name: phd-pa-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - pyarrow
  - duckdb
  - matplotlib
  - scikit-learn
  - pip:
      - rdflib
      - owlready2

